let fs= require('fs')
let path=require('path')
//fs.mkdirSync('customModule')
// console.log(path.join(__dirname,'customModule'),'\index.js')
 fs.writeFileSync(path.join(__dirname,'customModule','index.js'),'')